config/routes.rb
RunningProject::Application.routes.draw do
  devise_for :runners, controllers: { registrations: 'registrations'}

  #resources :trainings
  root 'trainings#main'

  resources :runners do
    resources :trainings
    resources :shoes
  end

  resources :tipos

  get 'allshoes' => 'shoes#main', :as => 'allshoes'
  
end

app/models/training.rb
class Training < ActiveRecord::Base
  after_initialize :default_values

	validates :description, :presence => true, :length => { :maximum => 140 }
	validates :comments, :length => { :maximum => 140 }
	belongs_to :runner
	validates :runner, :presence => true

  belongs_to :shoe

  validates :kms, presence: true, numericality: {greater_than_or_equal_to: 0.01, less_than_or_equal_to: 50.00}
  validates :hours, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 9  }
	validates :minutes, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 59 }
	validates :seconds, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 59 }

  private
    def default_values
      self.hours ||= 0
      self.minutes ||= 0
      self.seconds ||= 0
    end

    def self.latest
      Training.order(:updated_at).last
    end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]
  before_filter :get_runner, except: [:main]
  #after_save :set_kms, only: [:create] #falta el update o no?
  #before_action :set_time, only: [:edit, :update]
  #before_action :get_shoes, only: [:create, :edit, :update]


  def main
    @trainings = Training.limit(12).order(date: :desc)
    #En el root muestro los 12 últimos entrenamientos, de quien sean
  end

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = @runner.trainings #.limit(16).order(date: :desc) #esto no funciona si son del mismo dia
    @training = Training.new
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    #Suficiente con el set_training en el before_action
  end

  # GET /trainings/new
  def new
    #@training = Training.new
    #redirect_to @runner
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = @runner.trainings.new(training_params)
    @training.time = set_time(training_params) #calculate the total amount of seconds with hours, minutes and seconds
    respond_to do |format|
      if @training.save
        if @training.shoe
           @training.shoe.add_kms(@training.kms)
        end
        format.html { redirect_to runner_trainings_path, notice: '¡Entrenamiento creado!' }
        format.json { render action: 'show', status: :created, location: @training } #Esto hay que cambiarlo creo
      else
        format.html { render action: 'new' }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
      #format.js #Para el formulario de Nuevo Entrenamiento en el Show de Runner
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    #set_time
    #tiempoActual = @training.time
    zapatillaAnterior = @training.shoe
    if zapatillaAnterior
      logger.info("Zapatilla Anterior!!!!!!!!!!!!")
      logger.info(zapatillaAnterior.nombre)
    end
    kmsAnterior = @training.kms
    @training.time = set_time(training_params)
    respond_to do |format|
      if @training.update(training_params)
        logger.info("Zapatilla Nueva!!!!!!!!!!!!")
        zapatillaNueva = @training.shoe
        logger.info(zapatillaNueva.nombre)
        zapatillaNueva.add_kms(@training.kms) #Sumo los kms a la nueva zapatilla y salvo
        logger.info("Kilometros SUMADOS!!!!!!")
        if zapatillaAnterior
          zapatillaAnterior.subtract_kms(kmsAnterior) #Resto los kms del entreno anterior y salvo
          logger.info("Kilometros RESTADOS!!!!!!")
        end
        format.html { redirect_to runner_trainings_path, notice: 'Entreno actualizado!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
      if @training.destroy
        if @shoe #si el entrenamiento tiene zapatilla registrada
          @shoe.subtract_kms(@training.kms) #Quito los kms a la zapatilla
        end
      
        respond_to do |format|
          format.html { redirect_to runner_trainings_path }
          format.json { head :no_content }
          format.js
        end
      else
        respond_to do |format|
          format.html { redirect_to runner_trainings_path, notice: 'No puedes borrar este entrenamiento' }
          format.json { head :no_content }
          #format.js
        end
      end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    def set_shoe
      @shoe = nil #shoe is undefined
      if @training.shoe_id
        @shoe = Shoe.find(@training.shoe_id)
      end     
    end

    def get_runner #también selecciona sus zapatillas disponibles
      @runner = Runner.find(params[:runner_id])
      @my_shoes = Shoe.where(runner_id: params[:runner_id])
    end

    def actualizarKms(zAnt,zNueva,kmsAnt,kmsNuevos)
      if (zAnt == nil) && (zNueva == nil)
          #nada que actualizar
      elsif (zAnt == nil) && (zNueva)
        zNueva.totalkms += kmsNuevos
        zNueva.save
      elsif (zNueva == nil) && (zAnt)
        zAnt.totalkms -= kmsAnt
        zAnt.save
      elsif (zAnt == zNueva) 
        zNueva.totalkms -= kmsAnt
        zNueva.totalkms += kmsNuevos
        zNueva.save
      elsif (zAnt != zNueva)
        zAnt.totalkms -= kmsAnt
        zNueva.totalkms += kmsNuevos
        zAnt.save
        zNueva.save
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:kms, :time, :date, :runner_id, :shoe_id, :description, :comments, :hours, :minutes, :seconds)
    end
 
    def set_time(t)
      #Calculate the amount of seconds
      time = (t[:hours].to_i)*3600 + (t[:minutes].to_i)*60 + (t[:seconds].to_i)
    end

end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_for([@runner, @training]) do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% @training.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kms %><br>
    <%= f.text_field :kms, :autofocus => true, :placeholder => "Example 15.41" %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.number_field :hours %>
  </div>
  <div class="field">
    <%= f.label :minutes %><br>
    <%= f.number_field :minutes %>
  </div>
  <div class="field">
    <%= f.label :seconds %><br>
    <%= f.number_field :seconds %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :shoe %><br>
    <% if @my_shoes.empty?%>
    <%= f.label "No hay zapatillas" %>
    <% else %>
    <%= f.collection_select :shoe_id, @my_shoes, :id, :nombre, {prompt: "Selecciona"} %>  
    <% end %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
   <!-- <%= f.select :description, ['CC','Series','Competición'] %>-->
    <%= f.collection_select :description, Tipo.all, :nombre, :nombre, {prompt: "Selecciona el tipo"} %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainings/_training.html.erb
<!-- Entrenamiento -->
      <%= div_for training do %>
        <div class="arriba container">
          <h4 class="kms" data-kms=<%= sprintf("%0.02f", training.kms).to_s %> >
            <%= sprintf("%0.02f", training.kms) %><span> km</span>
          </h4>          
          <h4 class="time"><%= "Tiempo: " + time=hms(training.time) %></h4>
        </div>
        <div class="zapatillas container">
            <% if training.shoe %>
              <%= link_to truncate(training.shoe.nombre.titleize, length:30, separator: ' ', omission: ''), [training.runner, training.shoe] %>
            <% else %>
              <p>Unknown shoes</p>
            <% end %>
        </div>
        <div class="centro container">
          <div class="description">
            <p><%= training.description %></p>
          </div>
          <div class="comentarios">
            <% if training.comments.empty? %>
              <p>Sin comentarios</p>
            <% else %>
              <a class="enlacecomentarios">Comentarios</a>
              <!-- Comments tiene display none -->
              <p class="comments"><%= truncate(training.comments, length: 36, separator: ' ', omission: '...') %></p>
            <% end %>
          </div>  
        </div>
        <div class="abajo container">
          <h4 class="date"><%= training.date %></h4>
          <div class="acciones container">
            <% if training.runner == current_runner %>
              <ul><li><%= link_to '¿Editar?', edit_runner_training_path(training.runner, training) %></li>
              <li><%= link_to '¿Eliminar?', [training.runner, training], method: :delete, remote: true, data: { confirm: '¿Seguro?' }%></li></ul>
            <% else %>
              <% atleta = Runner.find(training.runner)%>
              <%= link_to truncate(atleta.name, length: 24, separator: ' ', omission: ''), runner_path(training.runner) %>
            <% end %>   
          </div>
        </div>
      <% end %>
<!-- Fin Entrenamiento -->

app/views/trainings/create.js.erb
$('div#entrenosrunner header').append("<%= escape_javascript(render @training) %>");
$('div#<%= dom_id(@training) %>').fadeIn('slow');

app/views/trainings/destroy.js.erb
$('#<%= dom_id(@training) %>').fadeOut();

app/views/trainings/edit.html.erb
<h1>Editando entrenamiento de <%= @runner.name.titleize %></h1>

<%= render 'form' %>

<%= link_to 'Ver todos', runner_trainings_path %>

app/views/trainings/index.html.erb
<% if current_runner == @runner %>
  <!-- Formulario para nuevo entrenamiento -->
  <h3>¿Tienes un nuevo entrenamiento?</h3>
  <div id="nuevoentreno" class="container">
      
    <%= form_for([@runner, @training]) do |f| %> <!-- He quitado remote: true porque no salía ordenado -->
      <% if @training.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>

          <ul>
          <% @training.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="formup container">
        <div class="smallfield">
          <%= f.label :kms %><br>
          <%= f.text_field :kms %>
        </div>
        <div class="smallfield">
          <%= f.label :hours %><br>
          <%= f.number_field :hours %>
        </div>
        <div class="smallfield">
          <%= f.label :minutes %><br>
          <%= f.number_field :minutes %>
        </div>
        <div class="smallfield">
          <%= f.label :seconds %><br>
          <%= f.number_field :seconds %>
        </div>
      </div>
      <div class="formmiddle container ">
        <div class="mediumfield">
          <%= f.label :date %><br>
          <%= f.date_select :date %>
        </div>
        <div class="normalfield">
          <%= f.label :shoe %><br>
          <% if @my_shoes.empty?%>
            <%= f.label "No hay zapatillas" %>
          <% else %>
            <%= f.collection_select :shoe_id, @my_shoes, :id, :nombre, {prompt: "Selecciona"} %>  
          <% end %>
        </div>
        <div class="normalfield">
          <%= f.label :description %><br>
         <!-- <%= f.select :description, ['CC','Series','Competición'] %>-->
          <%= f.collection_select :description, Tipo.all, :nombre, :nombre, {prompt: "Selecciona el tipo"} %>
        </div>
      </div>

      <div class="formdown container">
        <div class="bigfield">
          <%= f.label :comments %><br>
          <%= f.text_area :comments %>
        </div>
        <div class="buttondown">
          <%= f.submit %>
        </div>
      </div>
    <% end %>
  </div> 
  <!-- fin formulario nuevo entrenamiento -->
<% end %>

<div id="entrenosrunner" class="container">
  <% unless @trainings.empty? %>
    <header>
      <h3>Entrenamientos de <%= link_to @runner.name, @runner %></h3>
    </header>
    <%= render @trainings %>
  <% else %>
    <header>
      <h3>Sin entrenamientos</h3>
    </header>
  <% end %>
</div>

app/views/trainings/main.html.erb
<!-- Inicio Main  -->
<div id="entrenosrunner" class="container">
  <!-- He eliminado el cache porque no actualizaba la página, algo estaba mal-->
  <%= render @trainings %>
</div>
<!-- Fin Main -->

app/views/trainings/new.html.erb
<h1>New training for <%= @runner.name.titleize %>-<%= @runner.id %></h1>

<!--<%= render 'form' %>-->

<!--<%= link_to "Entrenos de #{@runner.name}", runner_trainings_path(@runner) %>-->

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kms:</strong>
  <%= sprintf("%0.02f", @training.kms) %>
</p>

<p>
  <strong>Tiempo:</strong>
  <%= hms(@training.time) %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @training.date %>
</p>

<p>
  <strong>Atleta:</strong>
  <%= link_to @training.runner.name.titleize, @runner %>
</p>

<p>
  <strong>Zapatillas:</strong>
  <% if @training.shoe %>
    <%= link_to @shoe.nombre, [@runner, @shoe] %>
  <% else %>
    undefined
  <% end %>
</p>


<p>
  <strong>Descripción:</strong>
  <%= @training.description %>
</p>

<p>
  <strong>Comentarios:</strong>
  <%= @training.comments %>
</p>

<%= link_to 'Editar', edit_runner_training_path(@runner, @training) %> |
<%= link_to 'Ver todos', runner_trainings_path(@runner) %> |
<%= link_to 'Eliminar', [@runner, @training], method: :delete %>