config/routes.rb
RunningProject::Application.routes.draw do
  devise_for :runners, controllers: { registrations: 'registrations'}

  #resources :trainings
  root 'trainings#main'

  resources :runners do
    resources :trainings
    resources :shoes
  end

  resources :tipos

  get 'allshoes' => 'shoes#main', :as => 'allshoes'
  
end

app/models/runner.rb
class Runner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #VALIDATIONS
	validates :name, :presence => true, :length => {:minimum => 6}
	validates :bio, :length => {:maximum => 140}
	validates :email, :uniqueness => true
  validates :datebirth, :presence => true
  #Check the minimum age
  validate :at_least_18


  #RELATIONSHIPS
	has_many :trainings,  dependent: :destroy
  has_many :shoes, dependent: :destroy

  
  #AVATAR
  #specify that the avatar is a paperclip file attachment
  #specify additional styles that you want to use in views or eslewhere
  has_attached_file :avatar, :styles => {:thumb => "100x100>"}
  
  #specify that the resume is a paperclip file attachment
  has_attached_file :resume

  has_attached_file :avatar, {
    :styles => {
      :thumb => ["50x50#", :png],
      :medium => ["100x100#", :png],
      :large => ["300x300>", :png]
    },
    :convert_options => {
      :thumb => "-gravity Center -crop 50x50+0+0",
      :thumb => "-gravity Center -crop 100x100+0+0",
    }
  }

  private

  def at_least_18
    if self.datebirth
      errors.add(:datebirth, 'Debes tener 18 años. Lo sentimos.') if self.datebirth > 18.years.ago.to_date
      # Si tu edad de nacimiento es más 'moderna' que hoy más 18 años
    end
  end

end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :authenticate_runner!, except: [:index]
  before_action :set_runner, only: [:show, :edit, :update, :destroy]
  before_action :get_records, only: [:show]

  # GET /runners
  # GET /runners.json
  def index
    @runners = Runner.all
  end

  def trainings
    @trainings = Training.where(:runner_id => @runner.id).order(date: :desc)
  end  

  # GET /runners/1
  # GET /runners/1.json
  def show
    if @runner
      @total = @trainings.count(:all)
    end
  end

  # GET /runners/new
  def new
    @runner = Runner.new
  end

  # GET /runners/1/edit
  def edit
  end

  # POST /runners
  # POST /runners.json
  def create
    @runner = Runner.new(runner_params)
    @runner.datebirth = params[:datebirth]

    respond_to do |format|
      if @runner.save
        format.html { redirect_to @runner, notice: 'Runner was successfully created.' }
        format.json { render action: 'show', status: :created, location: @runner }
      else
        format.html { render action: 'new' }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runners/1
  # PATCH/PUT /runners/1.json
  def update
    respond_to do |format|
      if @runner.update(runner_params)
        format.html { redirect_to @runner, notice: 'Runner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runners/1
  # DELETE /runners/1.json
  def destroy
    @runner.destroy
    respond_to do |format|
      format.html { redirect_to runners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_runner
      @runner = Runner.find_by_id(params[:id])
      @my_shoes = Shoe.where(runner_id: params[:id])
      @trainings = @runner.trainings
      @age = ((Date.today - @runner.datebirth).to_f / 365).floor
    end

    def get_records
      @tipo = ["Maratón", "Media Maratón", "10k", "5k"]
      @records = {maraton: nil, media: nil, diezK: nil}
      @records[:maraton] = Training.where("runner_id = ? and description = ?", params[:id], @tipo[0]).order(time: :desc).last
      @records[:media] = Training.where("runner_id = ? and description = ?", params[:id], @tipo[1]).order(time: :desc).last 
      @records[:diezK] = Training.where("runner_id = ? and description = ?", params[:id], @tipo[2]).order(time: :desc).last
      @records[:cincoK] = Training.where("runner_id = ? and description = ?", params[:id], @tipo[3]).order(time: :desc).last

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def runner_params
      params.require(:runner).permit(:name, :bio, :datebirth, :country, :avatar, :email, :password, :password_confirmation)
    end
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/runners/_form.html.erb
<!--<%= form_for(@runner) do |f| %>
  <% if @runner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
      <% @runner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %> -->

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
 <!-- <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>-->
  <div class="field">
    <%= f.label :datebirth %><br>
    <%= f.date_select :datebirth, start_year: 1970 %>
  </div>

  <!-- Upload your attachments via a simple file_fields in the form-->
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field medio">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field medio">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <!--<div class="actions">
    <%= f.submit %>
  </div>
<% end %>-->

app/views/runners/_formedit.html.erb
<%= form_for(@runner) do |f| %>
  <% if @runner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
      <% @runner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
 <!-- <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>-->
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :datebirth %><br>
    <%= f.date_select :datebirth, start_year: 1960 %>
  </div>
   <!-- Upload your attachments via a simple file_fields in the form-->
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <!-- Para cambiar contraseña tiene un formulario propio-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runners/_password.html.erb
<%= form_for(@runner) do |f| %>
  <% if @runner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
      <% @runner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label :password, "Contraseña" %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation, "Confirmar contraseña" %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Cambiar contraseña" %></div>
<% end %>

app/views/runners/edit.html.erb
<h1>Actualiza tus datos RUnner!</h1>

<%= render 'formedit' %>

<%= link_to 'Show', @runner %> |
<%= link_to 'Back', runners_path %>

app/views/runners/index.html.erb
<section id="listarunners" class="container">

<% unless @runners.empty? %>

  <header class="container">
    <h3>Estos son nuestros corredores, <%= link_to '¡Únete a ellos!', new_runner_registration_path %></h3>
  </header>

  <table>
    <thead>
      <tr> 
        <th>Nombre</th>
        <th>País</th>
        <th>Edad</th>
        <th>Bio</th>
      </tr>
    </thead>

    <tbody>
      <% @runners.each do |runner| %>
        <tr class="corredor">
          <td><%= link_to runner.name.titleize, runner %></td>
          <td><%= runner.country %></td>
          <% if runner.datebirth %>
            <td><%= runner.datebirth.to_s + " (" + ((Date.today - runner.datebirth).to_f/365).floor.to_s + ")" %></td>
          <% else %>
            <td>N/D</td>
          <% end %>  
          <td><%= runner.bio %></td>
          <!--<td><%= link_to 'Edit', edit_runner_path(runner) %></td>
          <td><%= link_to 'Destroy', runner, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <!-- Si no hay corredores, le ofrecemos ser el primero -->
  <header class="container">
    <h3><%= link_to '¿Quieres ser el primero?', new_runner_registration_path %></h3>
  </header>

<% end %>

</section>

app/views/runners/new.html.erb
<h1>New runner</h1>

<%= render 'form' %>

<%= link_to 'Back', runners_path %>

app/views/runners/show.html.erb
<% if @runner %>

<div id="contentrunner" class="container">

  <div class="avatar container">
    <%= image_tag @runner.avatar.url(:large) %>
  </div>

  <div id="datosrunner" class="container">
    <p>
      <strong>Nombre:</strong>
      <%= @runner.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @runner.email %>
    </p>

    <p>
      <strong>Bio:</strong>
      <%= @runner.bio %>
    </p>

    <p>
      <strong>Fecha de Nacimiento:</strong>
      <%= @runner.datebirth.to_s + " (" + @age.to_s + ")" %>
    </p>

    <p>
      <strong>País:</strong>
      <%= @runner.country %>
    </p>

    <% if @runner == current_runner %>
      <%= link_to 'Editar', edit_runner_path(current_runner) %>
      <%= link_to 'Cambia tu contraseña', edit_runner_registration_path %>
      <!--<%= link_to 'Borrar atleta', @runner, method: :delete %> -->
    <% end %>

  </div>
  <!-- fin datosrunner -->

  <div id="sesiones" class="container">
    <div id="realizadas">
      <!-- Tengo un @total con las sesiones que no se meter en el link_to-->
      <%= @total = @total.to_s; link_to "#{@total} Sesiones", runner_trainings_path(@runner) %>
      <h3>Récords personales</h3>
        <% if @records %>
          <ul>
            <li>Maratón: <%= hms(@records[:maraton].time) if @records[:maraton] %></li>
            <li>Media Maratón: <%= hms(@records[:media].time) if @records[:media] %></li>
            <li>10k: <%= hms(@records[:diezK].time) if @records[:diezK] %></li>
            <li>5k: <%= hms(@records[:cincoK].time) if @records[:cincoK] %></li>
            <!-- Poner un valor por defecto si no hay record -->
          </ul>
        <% else %>
          <p>No records yet</p>
        <% end %>
        <!-- Enlace a las zapatillas -->
        <% if @runner == current_runner %>
          <%= link_to 'Mis Zapatillas', runner_shoes_path(@runner) %>
        <% else %>
          <%= link_to 'Sus Zapatillas', runner_shoes_path(@runner) %>
        <% end %>
    </div>
    <!-- fin realizadas -->  
  </div>
  <!-- fin sesiones -->
</div>
<!-- fin contentRunner -->

<% else %>
  <p>No existe el corredor buscado</p>
<% end %>