config/routes.rb
RunningProject::Application.routes.draw do
  devise_for :runners, controllers: { registrations: 'registrations'}

  #resources :trainings
  root 'trainings#main'

  resources :runners do
    resources :trainings
    resources :shoes
  end

  resources :tipos

  get 'allshoes' => 'shoes#main', :as => 'allshoes'
  
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  validates :nombre, :presence => true, :length => {:maximum => 20}
  validates :descripcion, :presence => true, :length => {:maximum => 50}
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :authenticate_runner!
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to tipos_url, notice: 'Tipo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tipo }
      else
        format.html { render action: 'new' }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runners/1
  # PATCH/PUT /runners/1.json
  def update
    respond_to do |format|
      if @tipo.update(runner_params)
        format.html { redirect_to @tipo, notice: 'Tipo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:nombre, :descripcion)
    end
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipos/_form.html.erb
<%= form_for(@tipo) do |f| %>
  <% if @tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
      <% @tipo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipos/index.html.erb
<header>
<h3>Lista de tipos</h3>
</header>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= link_to tipo.nombre, tipo %></td>
        <td><%= tipo.descripcion %></td>
        <td><%= link_to 'Edit', edit_tipo_path(tipo) %></td>
        <td><%= link_to 'Destroy', tipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo tipo', new_tipo_path %>

app/views/tipos/new.html.erb
<h1>Nuevo tipo de entrenamiento/carrera</h1>

<%= render 'form' %>

<%= link_to 'Back', tipos_path %>

app/views/tipos/show.html.erb
<h1>Tipo de entrenamiento/Carrera</h1>

<h3><%= @tipo.nombre %></h3>
<h3><%= @tipo.descripcion %></h3>

<%= link_to 'Ver todos', tipos_path %>