config/routes.rb
RunningProject::Application.routes.draw do
  devise_for :runners, controllers: { registrations: 'registrations'}

  #resources :trainings
  root 'trainings#main'

  resources :runners do
    resources :trainings
    resources :shoes
  end

  resources :tipos

  get 'allshoes' => 'shoes#main', :as => 'allshoes'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Running Project</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<section id="header" class="container">
  <figure id="logo">
    <%= image_tag "berlin.jpg" %>
  </figure>
  <h2 id="mainlink">
	  <%= link_to 'The Running Project v1.0', root_url %>
  </h2>

  <nav id="menuinicio">
  <% if runner_signed_in? %>
    <p>Bienvenido <%= current_runner.name %></p>
    <%= link_to 'Cerrar Sesión', destroy_runner_session_path, method: :delete %>
    <%= link_to 'Mi perfil', runner_path(current_runner) %>
    <%= link_to 'Nuevo entrenamiento', runner_trainings_path(current_runner) %>
    <%= link_to 'Mis zapatillas', runner_shoes_path(current_runner) %>
  <% else %>
    <%= link_to 'Iniciar Sesión', new_runner_session_path %>
    <%= link_to 'Crear Cuenta', new_runner_registration_path %>  
    <%= link_to 'Nuestros Runners', runners_path %>
    <%= link_to 'Sus Zapatillas', allshoes_path %>
  <% end %>

  </nav>

</section>

<div id="avisos" class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

<%= yield %>

<footer>
  <h4>Code by <a href="http://www.elyunquevirtual.com">ElYunqueVirtual</a></h4>
</footer>

</body>
</html>